name: aarch64_torch_env
channels:
  - defaults
dependencies:
  - python=3.10
  - ninja==1.11.1
  - patchelf==0.17.2
  - pygit2
  - pyyaml
  - scons
  - conda-forge::zip
  - conda-forge::libarchive
  - conda-forge::libmamba
  - conda-forge::conda-libmamba-solver
  - conda-forge::libmambapy
  - typing_extensions

